import fs from "node:fs/promises";
import { pathToFileURL } from "node:url";

function yamlString(value) {
  return JSON.stringify(value);
}

function pluginUrl(pluginPath) {
  return yamlString(pathToFileURL(pluginPath).href);
}

export function renderPluginPatch({
  progressPlugin,
  googlePlacesPlugin,
  googleRoutesPlugin,
  googleMapsEnabled,
  googleRoutesEnabled,
  supervisorPrompt,
}) {
  return `# Generated by TripForge. Do not add secrets to this file.
- id: system-prompt
  config:
    persona: ${yamlString(supervisorPrompt)}

- insert:
    - id: tripforge-progress
      name: ${pluginUrl(progressPlugin)}
      inject: [tools, sessions]

    - id: tripforge-google-places
      name: ${pluginUrl(googlePlacesPlugin)}
      disabled: ${googleMapsEnabled ? "false" : "true"}
      inject: [tools, systemPrompt]
      config:
        apiKeyEnv: GOOGLE_MAPS_API_KEY
        maxResults: 8
        timeoutMs: 15000

    - id: tripforge-google-routes
      name: ${pluginUrl(googleRoutesPlugin)}
      disabled: ${googleRoutesEnabled ? "false" : "true"}
      inject: [tools, systemPrompt]
      config:
        apiKeyEnv: GOOGLE_MAPS_API_KEY
        maxStops: 10
        timeoutMs: 20000
`;
}

export async function writePluginPatch(filePath, options) {
  await fs.writeFile(filePath, renderPluginPatch(options), "utf8");
}
