"use client";

import { FormEvent, useState } from "react";
import type {
  AnswerValue,
  ClarificationOption,
  ClarificationQuestion,
  ClarificationResult,
  DateRangeAnswer,
} from "@/lib/trip-api/types";
import styles from "@/app/chat/new/chat.module.css";

function answerError(question: ClarificationQuestion, answer: AnswerValue | undefined) {
  if (question.kind === "date_range") {
    if (!isDateRangeAnswer(answer) || !answer.start_date || !answer.end_date) {
      return question.required ? "Choose both a start date and an end date." : "";
    }
    if (answer.end_date < answer.start_date) return "End date must be on or after the start date.";
    return "";
  }
  const empty = answer === undefined
    || answer === null
    || (Array.isArray(answer) ? answer.length === 0 : String(answer).trim().length === 0);
  if (empty) return question.required ? "Choose an option or add your answer." : "";
  if (question.kind === "number") {
    const number = Number(answer);
    if (!Number.isFinite(number)) return "Enter a valid number.";
    if (question.min_value !== undefined && question.min_value !== null && number < question.min_value) {
      return `Enter ${question.min_value} or more.`;
    }
    if (question.max_value !== undefined && question.max_value !== null && number > question.max_value) {
      return `Enter ${question.max_value} or less.`;
    }
  }
  if (typeof answer === "string") {
    if (question.min_length && answer.length < question.min_length) {
      return `Use at least ${question.min_length} characters.`;
    }
    if (question.max_length && answer.length > question.max_length) {
      return `Use no more than ${question.max_length} characters.`;
    }
  }
  return "";
}

function isDateRangeAnswer(answer: AnswerValue | undefined): answer is DateRangeAnswer {
  return Boolean(
    answer
    && typeof answer === "object"
    && !Array.isArray(answer)
    && "start_date" in answer
    && "end_date" in answer,
  );
}

function normalizeQuestionControl(question: ClarificationQuestion): ClarificationQuestion {
  const combinedCounts = /(?:adult|traveler|guest).*(?:child|children)|(?:child|children).*(?:adult|traveler|guest)/iu;
  const compositionId = /(?:traveler|guest).*(?:composition|breakdown)/iu;
  if (!combinedCounts.test(question.prompt) && !compositionId.test(question.id)) return question;
  return {
    ...question,
    kind: "text",
    placeholder: question.placeholder ?? "For example: 2 adults and 1 child",
    min_value: undefined,
    max_value: undefined,
    step: undefined,
  };
}

function StarIcon() {
  return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="m12 3 2.7 5.5 6.1.9-4.4 4.3 1 6.1-5.4-2.9-5.4 2.9 1-6.1-4.4-4.3 6.1-.9L12 3Z" /></svg>;
}

function MapPinIcon() {
  return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 21s6-5.2 6-11a6 6 0 1 0-12 0c0 5.8 6 11 6 11Z" /><circle cx="12" cy="10" r="2" /></svg>;
}

function CheckIcon() {
  return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 12 4 4 8-9" /></svg>;
}

function compactCount(value: number) {
  return new Intl.NumberFormat(undefined, { notation: "compact", maximumFractionDigits: 1 }).format(value);
}

function priceLabel(value?: string | null) {
  if (!value) return null;
  return value
    .replace("PRICE_LEVEL_", "")
    .replaceAll("_", " ")
    .toLowerCase()
    .replace(/^./u, (letter) => letter.toUpperCase());
}

function HotelChoice({
  option,
  selected,
  disabled,
  onSelect,
}: {
  option: ClarificationOption;
  selected: boolean;
  disabled: boolean;
  onSelect: () => void;
}) {
  const price = priceLabel(option.price_level);
  return <article className={`${styles.hotelChoice} ${selected ? styles.hotelChoiceSelected : ""}`}>
    <button type="button" disabled={disabled} aria-pressed={selected} onClick={onSelect}>
      <span className={styles.hotelChoiceImage}>
        <span>{option.label.slice(0, 2).toUpperCase()}</span>
        {option.image_url && <>
          {/* The URL is generated by FastAPI and served through TripForge's same-origin proxy. */}
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={option.image_url}
            alt={option.image_alt ?? `${option.label} hotel`}
            loading="lazy"
            decoding="async"
            onError={(event) => { event.currentTarget.hidden = true; }}
          />
        </>}
      </span>
      <span className={styles.hotelChoiceBody}>
        <span className={styles.hotelChoiceTitle}>
          <strong>{option.label}</strong>
          <i aria-hidden="true"><CheckIcon /></i>
        </span>
        {(option.rating != null || option.review_count != null) && <span className={styles.hotelChoiceRating}>
          <StarIcon />
          {option.rating != null && <strong>{option.rating.toFixed(1)}</strong>}
          {option.review_count != null && <small>{compactCount(option.review_count)} reviews</small>}
        </span>}
        {option.address && <span className={styles.hotelChoiceAddress}><MapPinIcon />{option.address}</span>}
        {option.description && <small className={styles.hotelChoiceDescription}>{option.description}</small>}
        {price && <span className={styles.hotelChoicePrice}>{price}</span>}
      </span>
    </button>
    <footer>
      <span>{selected ? "Selected stay" : "Select this stay"}</span>
      <span>
        {option.image_attribution && (option.image_attribution_url
          ? <a href={option.image_attribution_url} target="_blank" rel="noreferrer">Photo: {option.image_attribution}</a>
          : <small>Photo: {option.image_attribution}</small>)}
        {option.maps_url && <a href={option.maps_url} target="_blank" rel="noreferrer">Google Maps</a>}
      </span>
    </footer>
  </article>;
}

export function ClarificationForm({
  clarification,
  disabled,
  onSubmit,
}: {
  clarification: ClarificationResult;
  disabled: boolean;
  onSubmit: (answers: Record<string, AnswerValue>) => Promise<void>;
}) {
  const [step, setStep] = useState(0);
  const [answers, setAnswers] = useState<Record<string, AnswerValue>>({});
  const [otherQuestions, setOtherQuestions] = useState<Record<string, boolean>>({});
  const [validation, setValidation] = useState("");
  const question = normalizeQuestionControl(clarification.questions[step]);
  const isLast = step === clarification.questions.length - 1;
  const multiple = question.kind === "multi_select";

  function update(value: AnswerValue) {
    setAnswers((current) => ({ ...current, [question.id]: value }));
    setValidation("");
  }

  function continueStep() {
    const error = answerError(question, answers[question.id]);
    if (error) {
      setValidation(error);
      return;
    }
    setValidation("");
    setStep((current) => Math.min(current + 1, clarification.questions.length - 1));
  }

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!isLast) return continueStep();
    const error = answerError(question, answers[question.id]);
    if (error) {
      setValidation(error);
      return;
    }
    await onSubmit(answers);
  }

  const currentAnswer = answers[question.id];
  const usesOptions = (question.kind === "single_select" || multiple) && question.options.length > 0;
  const usesHotelCards = question.id === "hotel_selection"
    && question.kind === "single_select"
    && question.options.length > 0;
  const usingOther = Boolean(otherQuestions[question.id]);
  const descriptionId = question.description ? `${question.id}-description` : undefined;

  const dateRange = isDateRangeAnswer(currentAnswer)
    ? currentAnswer
    : { start_date: "", end_date: "" };
  const customField = question.kind === "date_range"
    ? <fieldset className={styles.dateRangeFields} aria-describedby={descriptionId}>
        <legend className={styles.srOnly}>Travel dates</legend>
        <label>
          <span>Start date</span>
          <input
            autoFocus
            disabled={disabled}
            type="date"
            value={dateRange.start_date}
            onChange={(event) => update({ ...dateRange, start_date: event.target.value })}
          />
        </label>
        <label>
          <span>End date</span>
          <input
            disabled={disabled}
            type="date"
            min={dateRange.start_date || undefined}
            value={dateRange.end_date}
            onChange={(event) => update({ ...dateRange, end_date: event.target.value })}
          />
        </label>
      </fieldset>
    : question.kind === "textarea"
    ? <textarea
        autoFocus
        disabled={disabled}
        rows={4}
        minLength={question.min_length ?? undefined}
        maxLength={question.max_length ?? 6000}
        value={typeof currentAnswer === "string" ? currentAnswer : ""}
        placeholder={question.placeholder ?? "Add any details that will improve the trip"}
        aria-describedby={descriptionId}
        onChange={(event) => update(event.target.value)}
      />
    : <input
        autoFocus
        disabled={disabled}
        type={question.kind === "number" ? "number" : question.kind === "date" ? "date" : "text"}
        inputMode={question.kind === "number" ? "decimal" : undefined}
        min={question.kind === "number" ? question.min_value ?? undefined : undefined}
        max={question.kind === "number" ? question.max_value ?? undefined : undefined}
        step={question.kind === "number" ? question.step ?? "any" : undefined}
        minLength={question.min_length ?? undefined}
        maxLength={question.kind === "number" || question.kind === "date" ? undefined : question.max_length ?? 300}
        value={typeof currentAnswer === "string" || typeof currentAnswer === "number" ? currentAnswer : ""}
        placeholder={question.placeholder ?? (question.kind === "location" ? "City, region, or address" : "Type your answer")}
        aria-describedby={descriptionId}
        onChange={(event) => update(event.target.value)}
      />;

  return <form className={styles.clarificationStepper} onSubmit={submit} aria-label="Trip clarification">
    <header>
      <div>
        <span>Question {step + 1} of {clarification.questions.length}</span>
        <strong>{question.prompt}</strong>
        {question.description && <small id={descriptionId}>{question.description}</small>}
      </div>
      <div className={styles.stepDots} aria-hidden="true">
        {clarification.questions.map((item, index) => <i
          className={index <= step ? styles.stepDotActive : ""}
          key={item.id}
        />)}
      </div>
    </header>

    {question.kind === "boolean" ? <div className={styles.stepOptions}>
      {[{ value: true, label: "Yes" }, { value: false, label: "No" }].map((option) => <button
        className={currentAnswer === option.value ? styles.stepOptionSelected : ""}
        type="button"
        disabled={disabled}
        key={option.label}
        aria-pressed={currentAnswer === option.value}
        onClick={() => update(option.value)}
      ><strong>{option.label}</strong></button>)}
    </div> : usesHotelCards && !usingOther ? <div className={styles.hotelChoiceList} role="group" aria-label={question.prompt}>
      {question.options.map((option) => <HotelChoice
        key={option.value}
        option={option}
        selected={currentAnswer === option.value}
        disabled={disabled}
        onSelect={() => update(option.value)}
      />)}
    </div> : usesOptions && !usingOther ? <div className={styles.stepOptions}>
      {question.options.map((option) => {
        const selected = multiple
          ? Array.isArray(currentAnswer) && currentAnswer.includes(option.value)
          : currentAnswer === option.value;
        return <button
          className={selected ? styles.stepOptionSelected : ""}
          type="button"
          disabled={disabled}
          key={option.value}
          aria-pressed={selected}
          onClick={() => {
            if (!multiple) return update(option.value);
            const current = Array.isArray(currentAnswer) ? currentAnswer : [];
            update(selected
              ? current.filter((value) => value !== option.value)
              : [...current, option.value]);
          }}
        >
          <strong>{option.label}</strong>
          {option.description && <small>{option.description}</small>}
        </button>;
      })}
      {question.allow_other !== false && <button
        className={styles.stepOther}
        type="button"
        disabled={disabled}
        onClick={() => {
          setOtherQuestions((current) => ({ ...current, [question.id]: true }));
          update("");
        }}
      >Other</button>}
    </div> : <div className={styles.stepCustomAnswer}>
      {customField}
      {usesOptions && <button type="button" disabled={disabled} onClick={() => {
        setOtherQuestions((current) => ({ ...current, [question.id]: false }));
        update("");
      }}>Show choices</button>}
    </div>}

    <footer>
      <span className={styles.stepValidation} role="alert">{validation}</span>
      <div>
        {step > 0 && <button type="button" disabled={disabled} onClick={() => setStep((current) => current - 1)}>Back</button>}
        <button className={styles.stepContinue} type="submit" disabled={disabled}>
          {disabled ? "Checking…" : isLast ? "Send answers" : "Next"}
        </button>
      </div>
    </footer>
  </form>;
}
